---
# Sample Config File
experiment: test
experts:
  - !!com.config.loader.experts.AExpert
    models:
      - !!com.config.loader.model.AModel
        &amodelbase
        aValue: 2
  - !!com.config.loader.experts.BExpert
      models:
        - !!com.config.loader.model.AModel
          <<: *amodelbase
          aValue2: 4
        - !!com.config.loader.model.BModel
          bValue: 1