# References work at per-document level
---
# Experience 1 Config File
experience: base_experience
experts:
  - !aExpert
    models:
      - !aModel
        &amodelbase
        aValue: 2
  - !bExpert
      models:
        - !aModel
          <<: *amodelbase
          aValue2: 4
        - !bModel
          bValue: 1
---
# Experience 2 Config File
experience: new_experience
experts:
  - !aExpert
    models:
      - !bModel
        bValue2: 2
  - !bExpert
      models:
        - !aModel
          aValue2: 3
        - !bModel
          bValue: 5